name: vidur
channels:
  - conda-forge
  - plotly
  - nodefaults
dependencies:
  - python=3.10
  - setuptools
  - pip
  - numpy
  - plotly_express
  - jupyterlab
  - matplotlib
  - pyyaml
  - snakeviz
  - scikit-learn
  - python-kaleido
  - wandb
  - fasteners
  - ray-all
  - streamlit
  - randomname
  - pip:
      - kaleido==0.2.1
      - ddsketch
      - paretoset
